# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/AD9767_SIN.xdc

# IP: ip/rom_ip/rom_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_ip || ORIG_REF_NAME==rom_ip} -quiet] -quiet
