# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/sd_picture_vga.xdc

# IP: ip/ddr3/ddr3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr3 || ORIG_REF_NAME==ddr3} -quiet] -quiet

# IP: ip/afifo_64i_32o_256/afifo_64i_32o_256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo_64i_32o_256 || ORIG_REF_NAME==afifo_64i_32o_256} -quiet] -quiet

# IP: ip/afifo_32i_64o_512/afifo_32i_64o_512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo_32i_64o_512 || ORIG_REF_NAME==afifo_32i_64o_512} -quiet] -quiet

# IP: ip/video_pll/video_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==video_pll || ORIG_REF_NAME==video_pll} -quiet] -quiet

# IP: ip/clk_200M/clk_200M.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_200M || ORIG_REF_NAME==clk_200M} -quiet] -quiet
