# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/sd_picture_vga.xdc

# IP: ip/afifo_64i_32o_128/afifo_64i_32o_128.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo_64i_32o_128 || ORIG_REF_NAME==afifo_64i_32o_128} -quiet] -quiet

# IP: ip/afifo_32i_64o_256/afifo_32i_64o_256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo_32i_64o_256 || ORIG_REF_NAME==afifo_32i_64o_256} -quiet] -quiet
