############# NET - IOSTANDARD ######################
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design] 
set_property CONFIG_MODE SPIx4 [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design] 
############## clock define###########################
create_clock -period 20 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {sys_clk}]
set_property PACKAGE_PIN Y18 [get_ports {sys_clk}]
#############reset Setting##########################
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN W9 [get_ports rst_n]
##############AD9767###########################
#############P1###########################
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da1_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports da1_wrt]
set_property IOSTANDARD LVCMOS33 [get_ports da1_clk]

set_property PACKAGE_PIN R19 [get_ports {da1_data[13]}]
set_property PACKAGE_PIN P19 [get_ports {da1_data[12]}]
set_property PACKAGE_PIN T18 [get_ports {da1_data[11]}]
set_property PACKAGE_PIN R18 [get_ports {da1_data[10]}]
set_property PACKAGE_PIN W22 [get_ports {da1_data[9]}]
set_property PACKAGE_PIN W21 [get_ports {da1_data[8]}]
set_property PACKAGE_PIN V20 [get_ports {da1_data[7]}]
set_property PACKAGE_PIN U20 [get_ports {da1_data[6]}]
set_property PACKAGE_PIN Y22 [get_ports {da1_data[5]}]
set_property PACKAGE_PIN Y21 [get_ports {da1_data[4]}]
set_property PACKAGE_PIN AA21 [get_ports {da1_data[3]}]
set_property PACKAGE_PIN AA20 [get_ports {da1_data[2]}]
set_property PACKAGE_PIN AB22 [get_ports {da1_data[1]}]
set_property PACKAGE_PIN AB21 [get_ports {da1_data[0]}]
set_property PACKAGE_PIN V19 [get_ports da1_wrt]
set_property PACKAGE_PIN V18 [get_ports da1_clk]
#############P2###########################
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da2_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports da2_wrt]
set_property IOSTANDARD LVCMOS33 [get_ports da2_clk]

set_property PACKAGE_PIN AA19 [get_ports {da2_data[13]}]
set_property PACKAGE_PIN AB20 [get_ports {da2_data[12]}]
set_property PACKAGE_PIN AA18 [get_ports {da2_data[11]}]
set_property PACKAGE_PIN AB18 [get_ports {da2_data[10]}]
set_property PACKAGE_PIN U17 [get_ports {da2_data[9]}]
set_property PACKAGE_PIN U18 [get_ports {da2_data[8]}]
set_property PACKAGE_PIN V17 [get_ports {da2_data[7]}]
set_property PACKAGE_PIN W17 [get_ports {da2_data[6]}]
set_property PACKAGE_PIN N17 [get_ports {da2_data[5]}]
set_property PACKAGE_PIN P17 [get_ports {da2_data[4]}]
set_property PACKAGE_PIN P15 [get_ports {da2_data[3]}]
set_property PACKAGE_PIN R16 [get_ports {da2_data[2]}]
set_property PACKAGE_PIN N13 [get_ports {da2_data[1]}]
set_property PACKAGE_PIN N14 [get_ports {da2_data[0]}]
set_property PACKAGE_PIN W20 [get_ports da2_wrt]
set_property PACKAGE_PIN W19 [get_ports da2_clk]