# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/VGA.xdc

# IP: ip/rom_word_ip/rom_word_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_word_ip || ORIG_REF_NAME==rom_word_ip} -quiet] -quiet
