//=======================================================
//  This code is generated by HX1006A Project Builder
//=======================================================

module CNT_5(

////////////CLOCK//////////
input 		          		CLK_50,

////////////SEG8//////////
output 		   [7:0]       	SEL,
output 		   [7:0]     	DIG,

////////////SW//////////
input 		     [3:0]		SW,

////////////KEY//////////
input 		     [3:0]		KEY,

////////////BEEP//////////
output 		          		BEEP 

);

wire clk_disp;
wire en, reset_n;
wire [31:0]q;
wire [31:0]m;

assign clk_disp = q[15];//2^16次分频
assign {en, reset_n} = KEY;
assign m = {4'd0, SW, 1'b1, 23'd0};

mcnt u_mcnt
(
	.clk		(CLK_50),
	.rst_n	(reset_n),
	.en		(en),
	.m			(m),
	.q			(q),
	.fout		(BEEP)
);

seg_disp u_seg_disp
(
	.clk		(clk_disp),
	.rst_n	(reset_n),
	.Q1		(q),
	.SEL		(SEL),
	.DIG		(DIG)
);


endmodule
