############# NET - IOSTANDARD ######################
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design] 
set_property CONFIG_MODE SPIx4 [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design] 
############## clock define###########################
create_clock -period 20 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property PACKAGE_PIN Y18 [get_ports {clk}]
#############reset Setting##########################
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN W9 [get_ports rst_n]
##############ADS8505###########################
#############DA CH1###########################
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports adc_rc]

set_property PACKAGE_PIN R19 [get_ports {data_in[15]}]
set_property PACKAGE_PIN P19 [get_ports {data_in[14]}]
set_property PACKAGE_PIN R19 [get_ports {data_in[13]}]
set_property PACKAGE_PIN P19 [get_ports {data_in[12]}]
set_property PACKAGE_PIN T18 [get_ports {data_in[11]}]
set_property PACKAGE_PIN R18 [get_ports {data_in[10]}]
set_property PACKAGE_PIN W22 [get_ports {data_in[9]}]
set_property PACKAGE_PIN W21 [get_ports {data_in[8]}]
set_property PACKAGE_PIN V20 [get_ports {data_in[7]}]
set_property PACKAGE_PIN U20 [get_ports {data_in[6]}]
set_property PACKAGE_PIN Y22 [get_ports {data_in[5]}]
set_property PACKAGE_PIN Y21 [get_ports {data_in[4]}]
set_property PACKAGE_PIN AA21 [get_ports {data_in[3]}]
set_property PACKAGE_PIN AA20 [get_ports {data_in[2]}]
set_property PACKAGE_PIN AB22 [get_ports {data_in[1]}]
set_property PACKAGE_PIN AB21 [get_ports {data_in[0]}]
set_property PACKAGE_PIN V19 [get_ports adc_rc]
