# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/dds.xdc

# IP: ip/rom_sawtooth_ip/rom_sawtooth_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_sawtooth_ip || ORIG_REF_NAME==rom_sawtooth_ip} -quiet] -quiet
