# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projects/FPGA/Vivado/DDS/DDS.srcs/sources_1/ip/rom_square_ip/rom_square_ip.xci
# IP: The module: 'rom_square_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/FPGA/Vivado/DDS/DDS.srcs/sources_1/ip/rom_square_ip/rom_square_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_square_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Projects/FPGA/Vivado/DDS/DDS.srcs/sources_1/ip/rom_square_ip/rom_square_ip.xci
# IP: The module: 'rom_square_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/FPGA/Vivado/DDS/DDS.srcs/sources_1/ip/rom_square_ip/rom_square_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_square_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
