############# NET - IOSTANDARD ######################
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design] 
set_property CONFIG_MODE SPIx4 [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design] 
############## clock define###########################
create_clock -period 20 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property PACKAGE_PIN Y18 [get_ports {clk}]
#############reset Setting##########################
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN W9 [get_ports rst_n]
########################VGA#########################
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_de]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_idck]

set_property PACKAGE_PIN C20 [get_ports {VGA_out[23]}]
set_property PACKAGE_PIN B21 [get_ports {VGA_out[22]}]
set_property PACKAGE_PIN B22 [get_ports {VGA_out[21]}]
set_property PACKAGE_PIN C22 [get_ports {VGA_out[20]}]
set_property PACKAGE_PIN D20 [get_ports {VGA_out[19]}]
set_property PACKAGE_PIN D21 [get_ports {VGA_out[18]}]
set_property PACKAGE_PIN D22 [get_ports {VGA_out[17]}]
set_property PACKAGE_PIN E21 [get_ports {VGA_out[16]}]
set_property PACKAGE_PIN E22 [get_ports {VGA_out[15]}]
set_property PACKAGE_PIN F20 [get_ports {VGA_out[14]}]
set_property PACKAGE_PIN F21 [get_ports {VGA_out[13]}]
set_property PACKAGE_PIN G21 [get_ports {VGA_out[12]}]
set_property PACKAGE_PIN G22 [get_ports {VGA_out[11]}]
set_property PACKAGE_PIN D14 [get_ports {VGA_out[10]}]
set_property PACKAGE_PIN D15 [get_ports {VGA_out[9]}]
set_property PACKAGE_PIN E16 [get_ports {VGA_out[8]}]
set_property PACKAGE_PIN C17 [get_ports {VGA_out[7]}]
set_property PACKAGE_PIN D17 [get_ports {VGA_out[6]}]
set_property PACKAGE_PIN E17 [get_ports {VGA_out[5]}]
set_property PACKAGE_PIN D19 [get_ports {VGA_out[4]}]
set_property PACKAGE_PIN E18 [get_ports {VGA_out[3]}]
set_property PACKAGE_PIN E19 [get_ports {VGA_out[2]}]
set_property PACKAGE_PIN E14 [get_ports {VGA_out[1]}]
set_property PACKAGE_PIN E13 [get_ports {VGA_out[0]}]
set_property PACKAGE_PIN F18 [get_ports VGA_hsync]
set_property PACKAGE_PIN F16 [get_ports VGA_vsync]
set_property PACKAGE_PIN F19 [get_ports VGA_de]
set_property PACKAGE_PIN D16 [get_ports VGA_idck]
########################KEY#########################
set_property IOSTANDARD LVCMOS33 [get_ports {key}]
set_property PACKAGE_PIN W6 [get_ports {key}]

set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN AA8 [get_ports {led[1]}]
set_property PACKAGE_PIN AB8 [get_ports {led[0]}]
